### ISSUE TITLE
Permissions and temp downloads folder

### ISSUE THREAD

**Issue by robflate** [RandomNinjaAtk/docker-amd#1]
Thanks for the script. I've got it setup and it's downloading and sending Lidarr import notifications, however I don't think I have the `DOWNLOADS` env variable set correctly and I'm also having permissions issues.

When AMD first creates the downloads folder, it is owned by root and when tracks are downloaded, AMD reports in the log that the folder does not exist;

<img width="1008" alt="Screenshot 2020-08-05 at 21 12 41" src="https://user-images.githubusercontent.com/4172375/89459557-bc0ca900-d760-11ea-82c0-ca9fd60b010e.png">

**AMD Log**
```
1 of 46 :: Four Tet :: 4T Recordings :: SEARCHING...
1 of 46 :: Four Tet :: 4T Recordings :: DOWNLOADING :: https://www.deezer.com/album/132511572
mv: cannot stat '/home/user/Docker/media-server/data/direct/lidarr-amd/amd/dlclient/*': No such file or directory
chmod: cannot access '/home/user/Docker/media-server/data/direct/lidarr-amd/amd/import/Four Tet - 4T Recordings (WEB)-132511572-deemix/*': No such file or directory
1 of 46 :: Four Tet :: 4T Recordings :: LIDARR IMPORT NOTIFICATION SENT! :: /home/user/Docker/media-server/data/direct/lidarr-amd/amd/import/Four Tet - 4T Recordings (WEB)-132511572-deemix
```
**Lidarr Log**
`Folder/File specified for import scan [/home/user/Docker/media-server/data/direct/lidarr-amd/amd/import/Four Tet - 4T Recordings (WEB)-132511572-deemix] doesn't exist.`

**docker-compose.yml**
```
  lidarr-amd:
    image: randomninjaatk/amd:latest
    container_name: lidarr-amd
    restart: unless-stopped
    network_mode: service:pia-vpn
    depends_on:
      - pia-vpn
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/user/Docker/media-server/config/lidarr-amd:/config
      - /home/user/Docker/media-server/data/direct/lidarr-amd:/downloads
    environment:
      PUID: 501
      PGID: 999
      TZ: Europe/London
      DOWNLOADS: "/home/user/Docker/media-server/data/direct/lidarr-amd"
      AUTOSTART: "true"
      LidarrUrl: "http://lidarr:8686"
      LidarrAPIkey: "redacted"
      MBRAINZMIRROR: "https://musicbrainz.org"
      MBRATELIMIT: 1
      ARL_TOKEN: "redacted"
      quality: "FLAC"
      FolderPermissions: 766
      FilePermissions: 666
```
If I `CHOWN` the download folder with 501:999 the 2 files that show as `Binary` become folders but the same errors still occur.

Apologies if I'm doing something stupid but any help appreciated. Thanks.
