### ISSUE TITLE
Config folders stay empty

### ISSUE THREAD

**Issue by BIoob** [RandomNinjaAtk/docker-amd#31]
Hey, just tried installing this, added it do my docker compose, the container starts without issues but the config folders are not being populated. The config directory gets created but it stays empty except for the deemix folder.

Here's my compose: 
 ```
  amd:
    image: randomninjaatk/amd 
    container_name: amd
    volumes:
      - /home/user/dockerconfigs/amd:/config
      - /home/user/NASMedia/Downloads/lidarr:/downloads-amd
    environment:
      - PUID=1000
      - PGID=1000
      - AUTOSTART=true
      - SCRIPTINTERVAL=1h
      - DOWNLOADMODE=wanted
      - LIST=both
      - SearchType=both
      - Concurrency=1
      - EMBEDDED_COVER_QUALITY=100
      - FORMAT=FLAC
      - BITRATE=320
      - ENABLEPOSTPROCESSING=true
      - FORCECONVERT=false
      - requirequality=true
      - MatchDistance=10
      - replaygain=true
      - FolderPermissions=766
      - FilePermissions=666
      - MBRAINZMIRROR=https://musicbrainz.org
      - MBRATELIMIT=1
      - LidarrUrl=http://192.168.0.xxx:8686
      - LidarrAPIkey=xxxxxxxxxxx
      - ARL_TOKEN=xxxxxxxxxxxxxxxxx
      - ALBUM_TYPE_FILTER=COMPILE
      - POSTPROCESSTHREADS=1
    restart: unless-stopped
 ```

Any idea what could be causing this?

When I try bash it says "bash: /config/scripts/download.bash: No such file or directory"

Edit: I just tried doing "docker exec -it amd /bin/bash" and then "ls" and the only directory showing inside the config folder is "deemix"
