### ISSUE TITLE
Restarting AMD is removing the entire downloads

### ISSUE THREAD

**Issue by acherifi** [RandomNinjaAtk/docker-amd#60]
Hi,

Each time AMD restarts (for a server upgrade or any other reason) the entire library is removed. Everything starts from scratch each time. 

What did I do wrong ? 
Here is my config 
```
amd:
    image: randomninjaatk/amd:latest 
    container_name: amd
    volumes:
      - amd_config:/config
      - /mnt/media/musicamd:/downloads-amd
    environment:
      - PUID=1000
      - PGID=1000
      - AUTOSTART=true
      - SCRIPTINTERVAL=1h
      - DOWNLOADMODE=wanted
      - FALLBACKSEARCH=True
      - LIST=both
      - SearchType=both
      - Concurrency=3
      - EMBEDDED_COVER_QUALITY=80
      - FORMAT=ALAC
      - BITRATE=320
      - ENABLEPOSTPROCESSING=true
      - FORCECONVERT=false
      - requirequality=true
      - MatchDistance=10
      - replaygain=true
      - FolderPermissions=777
      - FilePermissions=777
      - MBRAINZMIRROR=https://musicbrainz.org
      - MBRATELIMIT=1
      - LidarrUrl=http://192.168.1.214:8686
      - LidarrAPIkey=9d81f7689e0945728cd1aa5c79ad0da0
      - ARL_TOKEN=0f499720d7f72fd5db8209867ab7633b914965d0484c1b13d7631b681d928bbe393651e5541fddb73bd2f50dcf9117b3284475c239bc6cc72c67576b2f3c8e60c689ce99d38a40840be5443beaf766ec5459acafa7c4abc5572473960a692f8c
      - ALBUM_TYPE_FILTER=COMPILE
      - POSTPROCESSTHREADS=1
```
