### ISSUE TITLE
[ModuleNotFoundError] No module named 'deemix.app' 

### ISSUE THREAD

**Issue by IndependentFool** [RandomNinjaAtk/docker-amd#90]
### ModuleNotFoundError: No module named 'deemix.app'

**Issue:** 

This is a brand new install on Pop_OS 21.10 running the latest version of AMD in docker. During download the script errors with the above mentioned output. No files are downloaded and empty folders are created in the assigned folder. 

I see two previously closed issues relating to this #54 and #55 both marked as closed and solved.

This is my docker-compose config:

```
amd:
    image: halianelf/amd:latest
    container_name: amd
    networks:
      proxy:
        ipv4_address: 172.19.0.18
    logging:
      driver: json-file
      options:
        max-size: 200k
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/downloads/amd:/downloads-amd
      - /home/${USER}/docker/lidarr/amd:/config
    environment:
      - ARL_TOKEN=${TOKEN}
      - AUTOSTART=true
      - BITRATE=128
      - CONCURRENCY=1
      - DOWNLOADMODE=wanted
      - FILEPERMISSIONS=644
      - FOLDERPERMISSIONS=755
      - FORMAT=MP3
      - LIDARRAPIKEY=${LIDAR_API}
      - LIDARRURL=http://lidarr:8686
      - LIST=both
      - MATCHDISTANCE=10
      - MBRAINZMIRROR=https://musicbrainz.org
      - MBRATELIMIT=1
      - PGID=1000
      - PUID=1000
      - REPLAYGAIN=true
      - REQUIREQUALITY=true
      - SCRIPTINTERVAL=5m
      - SEARCHTYPE=both
      - TZ=America/New_York
      - EMBEDDED_COVER_QUALITY=100
```

And this is the error that shows in the logs:

```
Traceback (most recent call last):
  File "/config/scripts/dlclient.py", line 8, in <module>
    from deemix.app import deemix
ModuleNotFoundError: No module named 'deemix.app'
```
